# Generated by Django 4.2.14 on 2024-11-27 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_colors_alter_product_sizes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='product_id',
            new_name='product',
        ),
    ]
