# Generated by Django 4.2.14 on 2024-12-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_transaction_id_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('canceled', 'Canceled'), ('delivered', 'Delivered'), ('shipped', 'Shipped'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
