# Generated by Django 4.2.14 on 2024-12-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_product_id_image_product'),
        ('order', '0002_order_is_paid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OderItem',
            new_name='OrderItem',
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.RenameField(
            model_name='address',
            old_name='country',
            new_name='country_region',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('canceled', 'Canceled'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
    ]
