# Generated by Django 4.2.14 on 2024-12-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_oderitem_orderitem_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Click', 'Click'), ('Payme', 'Payme'), ('Card', 'Card'), ('cart', 'Cart'), ('Paypal', 'Paypal')], max_length=20, null=True),
        ),
    ]
