# Generated by Django 4.2.14 on 2024-12-20 20:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coupon', '0004_coupon_user_alter_coupon_discount_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='user',
        ),
        migrations.AddField(
            model_name='coupon',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='use_coupons', to=settings.AUTH_USER_MODEL),
        ),
    ]
